version: '3'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: techteam
      MYSQL_PASSWORD: 123456Aa@
      MYSQL_ROOT_HOST: '%'
